name: Jupyter
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Setup Python 
      uses: actions/setup-python@v4.0.0
      with:
        cache: pip
        python-version: '3.8'
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Exeute Notebook 
      run: jupyter-nbconvert --execute Script_download.ipynb --to html
    - name: Upload a Build Artifact 
      uses: actions/upload-artifact@v3.1.0
      with:
        name: Artifact
        path: DZ1.html
